server:
  port: 8080
spring:
  application:
    name: GameVibes
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.138.154.250:3306/gamevibe?useSSL=false&serverTimezone=UTC
    username: gamevibe
    password: PESEbftdxRPBsFKk
  # Elasticsearch 配置
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
knife4j:
  enable: true
  basic:
    enable: true
    username: password
    password: username
casdoor:
  endpoint: http://localhost:8000
  client-id: 1f20ed3e6ad105928baf
  client-secret: 5a984039da5cf307fdb1dbc76321097561fe03d1
  certificate: |-
    -----BEGIN CERTIFICATE-----
    MIIE3TCCAsWgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCgxDjAMBgNVBAoTBWFk
    bWluMRYwFAYDVQQDEw1jZXJ0LWJ1aWx0LWluMB4XDTI0MDYwODE2MTUyMFoXDTQ0
    MDYwODE2MTUyMFowKDEOMAwGA1UEChMFYWRtaW4xFjAUBgNVBAMTDWNlcnQtYnVp
    bHQtaW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDdYMYi1yUtKgps
    YgNqrOZ1eEysTdcFrDzj5G1gWFoOBnYr/3ULg1n+4C5aoDkXVQrMqpDmJ9G4jkNu
    COlwbds70fCNHoumxkxar1GDP0Q64bnBnuPKWS2aBNLdtsOmibVQ/Hli9eq+xzgT
    u52bB7EfIUIp9wHBXhnMdcPB54wJGc2G6mAdMQLbWRmbf8y+FZDFWxx8SA1fOSZc
    7TlHRc6oobk2j5w1rzdodtD8GPdy0nkMEsv466+NOM/WedTzS7ddfhy88o+GnFiP
    r/uK0i8rfKYEFT+OaCnk6HEFGEu/vvhfi6ycUcL5V2BUWQJ26gyAHCY8qqCSLuhD
    p7xE1/KoRZ4w1EpWL/P2Nw0JpcMHvwjREK8x//ToTPgbYY1XnK0bX/8AIF6mvm7y
    CtJZb8Fdp9e93QVnfWwNrRUrlxKV0YpsbirtV9g7rmHrQzUIO9Uz50m0NqD06Phy
    WB/2+xLHIN7j2ck0NWGeSzNA2MrVZYj4+fbiIJJaNKMIpOIPd/FyItfeomem6u/I
    DfFHYIzaKy5c1N8LLGPRKI10aR6gw8n3CZeXjh+EBMBDyBuYQ2fkvjibBoj8GztS
    L5BXtwUh9a2lQ+xUQXIsUPFDm+0smqz6xdPBEYXTRAk8eCFYM3cfcYXpcXoSC74E
    bBdXKBLQKpl7LD5Yp3lVHTFAIefquwIDAQABoxAwDjAMBgNVHRMBAf8EAjAAMA0G
    CSqGSIb3DQEBCwUAA4ICAQAQ8X+U4TKy85uDC4FxtbWC0gEx4/2aaGSVcWASPBQ9
    tJXZdJ2gvlKQgwiz4cAA0Hg6UDEi7sezENnpixjn/KduIn4K5jXIEA9iMZfcr/8X
    z4tO92FwyvotAzbzomBETxHGr+26fJybfzrZCLwkICobJ4NmuSXOSiSJaGgsirSR
    IvBU86qJerEzPciVVrNi3IllMakIt3TRI+DrMTH3cX11EmjWivWgbuyaVxCPAu2n
    nz5dMPHkMK1ikfD6QoTJMKxsvJ9sw9wGD8WxqTOQy++i6sDJPtWtPaYk3e8d0AKF
    0rnUQ/VBxwNFkTLnHoecRUdxb2rlxzRbedoHDrIvccMi4V7Qa1j/jpyKen21O/vD
    Cme5Y7ybO+J6vPTwuYxJ7tPisMb/RzYo2f3n7YBw8dNd1CFICZRpC2RHFEk6i9wt
    2Sd1G4w0wChLJ1GVOpS1wVqt4Yvhg5yC+rE9k3Ml2b5tf6b4VS71kPy5+wXszXNB
    X6ME69MZYSHygZbaBAFAU6ekoBJDU68l681xEyiKmuEhUql/F1YYigc5QlCtUfEU
    S1D42kP9faNxM9GhEPj6juvYfSa4oo/BVoRtu4YFB5dhsfHCWwowiyTkSuEKF+1J
    ItQqZxxcDhhwwnzL152f1t+bgPH6kE+csbP7SdGBWm7JTUbI2zYVE9YVjmmOYIiO
    LQ==
    -----END CERTIFICATE-----
  organization-name: built-in
  application-name: app-built-in
  redirect-url: http://localhost:8080/api/signin